### PR TITLE
add support for thrift 0.10.0 

### PR DESCRIPTION
**Pull request by mpvartak**
#191 

Updated the server pom.xml to use newer version of thrift-maven-plugin.

### CODE REVIEW

**Comment by ghost** [comment]
Getting errors with this new merge... wiped my .m2/repository folder and I'm getting five build errors with ModelDBService.java that all look like:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project modeldb: Compilation failure: Compilation failure:
[ERROR] /root/modeldb_fork/server/target/generated-sources/thrift/modeldb/ModelDBService.java:[1453,18] error: testConnection_call is not abstract and does not override abstract method getResult() in TAsyncMethodCall
[ERROR] /root/modeldb_fork/server/target/generated-sources/thrift/modeldb/ModelDBService.java:[1465,17] error: getResult() in testConnection_call cannot override getResult() in TAsyncMethodCall
```

All five error messages refer to "XXX is not abstract and does not override abstract method getResult() in TAsyncMethodCall"

Build still works with thrift 0.9.3 and maven-thrift-plugin 0.1.11.

**Comment by mpvartak** [comment]
Will look into this. We may need two build file for the two thrift versions.

**Comment by mpvartak** [comment]
@arubisov any chance you could check if changing the version of libthrift and thrift-maven-plugin from 0.10.0 to 0.9.3 in the latest pom.xml fixes the issues for you? If so, I can make a quick fix.

**Comment by ghost** [comment]
Doesn't look like the thrift-maven-plugin version 0.9.3 can be used... error on build:
```
[ERROR] Failed to execute goal org.apache.thrift:thrift-maven-plugin:0.9.3:compile (thrift-sources) on project modeldb: The parameters '${project.build.directory}/thrift-dependencies' for goal org.apache.thrift:thrift-maven-plugin:0.9.3:compile are missing or invalid -> [Help 1]
```
Related JIRA issue: https://issues.apache.org/jira/browse/THRIFT-3419

I think the only way to use 0.9.3 is to build and install from source with the patch in that JIRA ticket.
